# Jekyll config file

# Site settings
title_short: DataCleaner
title: The premier open source Data Quality solution | DataCleaner
description: >
  Open source software for data quality, data profiling, data warehousing, data wrangling,
  master data management, business intelligence and governance.
releases: [
  {"version": "5.2.0"},
  {"version": "5.1.5"},
  {"version": "5.1.4"},
  {"version": "5.1.3"},
  {"version": "5.1.2"},
  {"version": "5.0.3"},
  {"version": "5.0.2"},
  {"version": "5.0"},
  {"version": "4.5"},
  {"version": "4.0.2"},
  {"version": "4.0.1"},
  {"version": "4.0"}
]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
